const unsigned char WebSide_home[] = {
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
"<html>"
"<head>\r\n"
	"<meta http-equiv= \"Content-Type\" content=\"text/html;charset=utf-8\" />\r\n"
"<title>MicroGrid | Homepage</title>\r\n"
"<style type=\"text/css\">\r\n"
	"body{margin-left:250px;width:800px;}\r\n"
	"p{font:20px Verdana;color:#006633;}\r\n"
	"hr{height:1px;border:none;border-top:1px ridge #339966;}\r\n"
	"iframe{width:800px;height:200px;border-style:none;scrolling:no;}\r\n"
	"a{color: white;font:bold 13px verdana;text-decoration:none;}\r\n"
	"ul{padding:0px;}\r\n"
	"ul li{background:#00CC33;display:inline;float: left;width: 160px;height:45px;text-align:center;list-style:none;line-height:45px;border:1px solid white;margin-left:-2px;}\r\n"
	"ul li a{line-height:45px;padding:0px;display:block;}\r\n"
	"ul li a:hover{background:#006633;}\r\n"
	".bottom{font-size: 13px; color: #339966;text-align: center; margin-top:10px;}\r\n"
	"#nav{height:50px;}\r\n"
	"#logo{margin-left:0px;}\r\n"
	"#kth{margin-left:265px;}\r\n"
	"#banner{margin-left:20px;margin-top:-80px;}\r\n"
"</style>"
"</head>\r\n"
"<body>"
"<div id=\"nav\">\r\n"
"<ul>\r\n"
	"<li><a href=\"index.html\">Monitoring</a></li>\r\n"
	"<li><a href=\"setting.html\">Setting</a></li>\r\n"
	"<li><a href=\"http://mgpcb.carenet-se.se/\">Backup Controller</a></li>\r\n"
	"<li><a href=\"http://ttaportal.org/menu/projects/microgrid/summer-2012/pcb-help-page\">Help</a></li>\r\n"
	"<li><a href=\"http://ttaportal.org/menu/projects/microgrid/summer-2012/\">About Us</a></li>\r\n"
"</ul>"
"</div>\r\n"
"<div id=\"logo\">"
	"<hr />"
	"<img src=\"http://i47.tinypic.com/28199k.jpg\"></img>"
"</div>\r\n"
"<div>\r\n"
	"<hr />\r\n"
	"<p>Main Controller Status: </p>\r\n"
	"<iframe id=\"data\" src=\"par.html\"></iframe>\r\n"
	"<input type=\"button\" value=\"Refresh\" onclick=\"document.getElementById(\'data\').src=\'par.html\';\">\r\n"
"</div>\r\n"
"<div>\r\n"
	"<hr />\r\n"
	"<img id=\"kth\" src= \"http://www.kth.se/polopoly_fs/1.77257!/image/logo-main.png\"></img>\r\n"
	"<img id=\"banner\" src=\"http://i48.tinypic.com/2mepqg0.jpg\"></img>\r\n"
	"<p class=\"bottom\">MicroGrid | All Rights Reserved</p>\r\n"
"</div>\r\n"
"</body>"
"</html>\r\n"
};

const unsigned char WebSide_par[] = {
"<html>\r\n"
"<head>"
	"<meta http-equiv=\"refresh\" content=\"5\">"
	"<script type= \"text/javascript\">\r\n"
		"var i=0;\r\n"
		"var today= new Date();\r\n"
		"var month= today.getMonth()+1;\r\n"
		"var setdate=today.getFullYear()+\"-\"+month+\"-\"+today.getDate();\r\n"
		"var settime=today.getHours()+\":\"+today.getMinutes()+\":\"+today.getSeconds();\r\n"
		"setTimeout(\"document.getElementById(\'td1\').innerHTML=setdate\",0);\r\n"
		"setTimeout(\"document.getElementById(\'td2\').innerHTML=settime\",0);\r\n"
		"setTimeout(\"document.getElementById(\'td3\').innerHTML=setdate\",0);\r\n"
		"setTimeout(\"document.getElementById(\'td4\').innerHTML=settime\",0);\r\n"
	"</script>\r\n"
	"<style type=\"text/css\">\r\n"
		"table{border-collapse:collapse;}\r\n"
		"th{width:130px;height:45px;text-align:center;font:bold 15px Verdana;color:#006633;border:1px solid #339966;background:#99FF66;}\r\n"
		"td{width:130px;height:40px;text-align:center;font:13px Verdana;color:#339966;border:1px dashed #339966;border-bottom:1px solid #339966;}\r\n"
		".left{border-left:1px solid #339966;}\r\n"
		".right{border-right:1px solid #339966;}\r\n"
	"</style>"
"</head>\r\n"
"<div>"
	"<table>"
		"<tr>\r\n"
			"<th>Date</th>\r\n"
			"<th>Time</th>\r\n"
			"<th>Vin</th>\r\n"
			"<th>Vout</th>\r\n"
			"<th>Iin</th>\r\n"
			"<th>Iout</th>\r\n"
		"</tr>\r\n"
		"<tr>\r\n"
			"<td class=\"left\" id=\"td1\"> </td>\r\n"
			"<td id=\"td2\"> </td>\r\n"
			"<td>AD1Oooo</td>\r\n"
			"<td>AD2Oooo</td>\r\n"
			"<td>AD3Oooo</td>\r\n"
			"<td class=\"right\">AD4Oooo</td>\r\n"
		"</tr>\r\n"
		"<tr>\r\n"
			"<th>Date</th>\r\n"
			"<th>Time</th>\r\n"
			"<th>Mode</th>\r\n"
			"<th>Vmax</th>\r\n"
			"<th>Imax</th>\r\n"
			"<th>Vref</th>\r\n"
		"</tr>\r\n"
		"<tr>\r\n"
			"<td class=\"left\" id=\"td3\"> </td>\r\n"
			"<td id=\"td4\"> </td>\r\n"
			"<td>AD6Oooo</td>\r\n"
			"<td>AD7Oooo</td>\r\n"
			"<td>AD8Oooo</td>\r\n"
			"<td class=\"right\">AD9Oooo</td>\r\n"
		"</tr>"
	"</table>"
"</div>"
"</html>"
		};

const unsigned char WebSide_Setting[] = {
		"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
		"<head>\r\n"
			"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n"
			"<title>MicroGrid | Settings</title>\r\n"
			"<script type=\"text/javascript\">\r\n"
				"function compare1 () {var Vref=document.settings1.vref;\r\n"
				"if((Vref.value<0)||(Vref.value>=26)){document.getElementsByName(\"Submit1\")[0].disabled=true;}else{document.getElementsByName(\"Submit1\")[0].disabled=false;}}\r\n"
				"function compare2 () {var mod=document.settings2.mode;\r\n"
				"if((mod.value !=0)&&(mod.value !=1)){document.getElementsByName(\"Submit2\")[0].disabled=true;}else{document.getElementsByName(\"Submit2\")[0].disabled=false;}}\r\n"
				"function compare3 () {var IMAX=document.settings3.imax;\r\n"
				"if ((IMAX.value<1)||(IMAX.value>7)){document.getElementsByName(\"Submit3\")[0].disabled=true;}else{document.getElementsByName(\"Submit3\")[0].disabled=false;}}\r\n"
				"function ShowHide(divId)\r\n"
				"{if(document.getElementById(divId).style.display==\"none\")\r\n"
				"{document.getElementById(divId).style.display=\"block\";}\r\n"
				"else{document.getElementById(divId).style.display=\"none\";}}\r\n"
			"</script>\r\n"
			"<style type=\"text/css\">\r\n"
				"body{margin-left:250px;width:800px;}\r\n"
				"ul{padding:0px;}\r\n"
				"ul a{color: white;font:bold 13px verdana;text-decoration:none;}\r\n"
				"ul li{background:#00CC33;display:inline;float: left;width: 160px;height:45px;text-align:center;list-style:none;line-height:45px;border:1px solid white;margin-left:-2px;}\r\n"
				"ul li a{line-height:45px;padding:0px;display:block;}\r\n"
				"ul li a:hover{background:#006633;}\r\n"
				"hr{height: 1px; border:none; border-top: 1px ridge #339966;}\r\n"
				"form{margin-top:20px;}\r\n"
				"#nav{margin-left:0px;height:50px;}\r\n"
				"#label{width:450px;height:60px;font-size:24px;margin-left:10px;text-align:left;color:#006633;}\r\n"
				"#content{width:450px;height:300px;font-size:18px;margin-top:20px;background:#E3F6CE;text-align:left;padding:15px;color:#006633;}\r\n"
				"#logo{margin-left:600px;margin-top:-350px;}\r\n"
				".intext{color:#006633;}\r\n"
			"</style>"
		"</head>\r\n"
		"<body>\r\n"
			"<div id=\"nav\">\r\n"
				"<ul>\r\n"
					"<li><a href=\"index.html\">Monitoring</a></li>\r\n"
					"<li><a href=\"setting.html\">Setting</a></li>\r\n"
					"<li><a href=\"http://mgpcb.carenet-se.se/\">Backup Controller</a></li>\r\n"
					"<li><a href=\"http://ttaportal.org/menu/projects/microgrid/summer-2012/pcb-help-page\">Help</a></li>\r\n"
					"<li><a href=\"http://ttaportal.org/menu/projects/microgrid/summer-2012/\">About Us</a></li>\r\n"
				"</ul>"
			"</div>\r\n"
			"<hr id=\"cutoff\"/>\r\n"
			"<div id=\"label\">\r\n"
				"<p>MicroGrid Settings</p>\r\n"
				"<hr />\r\n"
			"</div>\r\n"
			"<div id=\"content\">\r\n"
				"<form name=\"settings1\" method=\"POST\">\r\n"
					"<p>Please Enter Your Desired Voltage &#40V<sub>ref</sub>&#41:</p>\r\n"
					"<input name=\"vref\" type=\"text\" class=\"intext\" value=\"0 - 25\" onFocus=\"this.value=\'\'\" onkeyup=\"this.value=this.value.replace(/[^0-9.]/g,\'\');compare1 ()\">\r\n"
					"<input name=\"Submit1\" type=\"submit\" value=Submit>\r\n"
					"<input name=\"Reset\" type=\"reset\">\r\n"
				"</form>\r\n"
				"<form name=\"settings2\" method=\"POST\">\r\n"
					"<p>Please Enter Mode:</p>\r\n"
					"<input name=\"mode\" type=\"text\" class=\"intext\" value=\"0: Reverse, 1: Default\" onFocus=\"this.value=\'\'\" onkeyup=\"this.value=this.value.replace(/[^0-9.]/g,\'\');compare2 ()\">\r\n"
					"<input name=\"Submit2\" type=\"submit\" value=Submit>\r\n"
					"<input name=\"Reset\" type=\"reset\">\r\n"
				"</form>\r\n"
				"<form name=\"settings3\" method=\"POST\">\r\n"
					"<a onclick =\"javascript:ShowHide(\'HiddenDiv1\')\" href=\"javascript:;\" style=\"text-decoration: underline;\">Advanced Option</a>\r\n"
					"<div id=\"HiddenDiv1\" style=\"DISPLAY:none\">\r\n"
						"<p>Please Enter I<sub>max: </p>\r\n"
						"<input name=\"imax\" type=\"text\" class=\"intext\" value=\"1 - 7\" onFocus=\"this.value=\'\'\" onkeyup=\"this.value=this.value.replace(/[^0-9.]/g,\'\');compare3 ()\">\r\n"
						"<input name=\"Submit3\" type=\"submit\" value=Submit>\r\n"
						"<input name=\"Reset\" type=\"reset\">\r\n"
					"</div>\r\n"
				"</form>\r\n"
			"</div>\r\n"
			"<img id=\"logo\" src=\"http://i48.tinypic.com/9ko4ut.jpg\"></img>\r\n"
		"</body>\r\n"
		"</html>\r\n"
		};


const unsigned char WebSide_monitor[] = {
		 "HTTP/1.0 200 OK\r\n"
		 "Content-Type: text/html\r\n"
		 "\r\n"
		"<html>\r\n"
		"<head>\r\n"
		"<title>easyWEB - dynamic Webside</title>\r\n"
		"</head>\r\n"
		"\r\n"
		"<table border=\"1\">\r\n"
		"<tr>\r\n"
		"<td>AD6Oooo</td>\r\n"
		"<td>AD7Oooo</td>\r\n"
		"<td>AD8Oooo</td>\r\n"
		"<td>AD9Oooo</td>\r\n"
		"<td>AD1Oooo</td>\r\n"
		"<td>AD2Oooo</td>\r\n"
		"<td>AD3Oooo</td>\r\n"
		"<td>AD4Oooo</td>\r\n"
		"</tr>\r\n"
		"</table>\r\n"
		"</body>\r\n"
		"</html>\r\n"
		"\r\n"
};
